"""add usuarios_eliminados table

Revision ID: b2dadbb70624
Revises: bda93c111329
Create Date: 2025-04-16 10:29:08.496787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dadbb70624'
down_revision = 'bda93c111329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), nullable=False),
    sa.Column('contacto', sa.VARCHAR(length=255), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
