"""Agregar columnas descripcion y fecha_agregado a productos_inventario

Revision ID: bda93c111329
Revises: 7991cbd6ba47
Create Date: 2025-04-15 13:01:19.165490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda93c111329'
down_revision = '7991cbd6ba47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos_inventario', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
